version: '2'
services:
  ui:
    build: ./clientapp
    ports:
      - '3000:3000'
    depends_on:
      - api
  web:
    build: ./api
    ports:
      - '9000:9000'
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'